
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r packages/regression_model/requirements.txt
  displayName: 'Install requirements regression_model'

- script: |
    python packages/regression_model/setup.py sdist bdist_wheel
  displayName: 'Build package'

- script: |
    pip install -r requirements.txt
  displayName: 'Install package'

- script: |
    python packages/regression_model/regression_model/train_pipeline.py
  displayName: 'Train the model'

- script: |
    pip install pytest pytest-azurepipelines
    pytest packages/regression_model/tests
  displayName: 'Run tests'
